# Generated by Django 6.0.6 on 2026-07-26 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_returnrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10)),
                ('products', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10)),
                ('categories', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10)),
                ('customers', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10)),
                ('orders', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10)),
                ('inventory', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10)),
                ('payments', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10)),
                ('shipping', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10)),
                ('returns', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10)),
                ('reports', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
