# Generated by Django 6.0.6 on 2026-08-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_supplier_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceuserpermissions',
            name='suppliers',
            field=models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10),
        ),
    ]
