# Generated by Django 6.0.6 on 2026-08-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_ecommercenotification_supportticket_ticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceuserpermissions',
            name='support',
            field=models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10),
        ),
    ]
