# Generated by Django 6.0.6 on 2026-08-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_abandonedcart_abandonedcartitem_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceuserpermissions',
            name='documents',
            field=models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('full', 'Full Access')], default='none', max_length=10),
        ),
    ]
