# """
# Django settings for leadcrm project.

# Generated by 'django-admin startproject' using Django 6.0.5.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """

# import os
# from pathlib import Path
# from dotenv import load_dotenv

# load_dotenv()

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# SECRET_KEY = 'django-insecure-up)3d^nyft+z364r3rl+2@$qkld5a^)_i19e2f_uum)t9nfle*'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = ["*"]


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'leads',
#     'ecommerce',
#     'chatbot',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'leads.middleware.RoleAccessMiddleware',
# ]

# ROOT_URLCONF = 'leadcrm.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#                 'leads.context_processors.sidebar_counts'
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'leadcrm.wsgi.application'


# # Email (SMTP)
# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
# # EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
# # EMAIL_USE_TLS = True
# # EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
# # EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
# # DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False

# EMAIL_HOST_USER = 'your-email@example.com'

# # Gmail App Password
# EMAIL_HOST_PASSWORD = 'REMOVED-SECRET' 

# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# # Debug
# EMAIL_TIMEOUT = 30

# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR / 'static']

# LOGIN_URL = '/login/'
# LOGIN_REDIRECT_URL = '/'

# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# # Meta WhatsApp Cloud API
# META_WHATSAPP_TOKEN = os.getenv('META_WHATSAPP_TOKEN', '')
# META_PHONE_NUMBER_ID = os.getenv('META_PHONE_NUMBER_ID', '')
# META_VERIFY_TOKEN = os.getenv('META_VERIFY_TOKEN', 'leadcrm123')

# # Groq AI
# GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')

"""
Django settings for leadcrm project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
if os.environ.get('DJANGO_ENV', 'development') != 'production':
    os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
from pathlib import Path
from dotenv import load_dotenv
from decouple import config

import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'django-insecure-up)3d^nyft+z364r3rl+2@$qkld5a^)_i19e2f_uum)t9nfle*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = ['92.112.181.72', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'leads',
    'ecommerce',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'leads.middleware.RoleAccessMiddleware',
    'leadcrm.middleware.OrganizationAccessMiddleware',
]

ROOT_URLCONF = 'leadcrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'leads.context_processors.sidebar_counts'
            ],
        },
    },
]

WSGI_APPLICATION = 'leadcrm.wsgi.application'


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = 'your-email@example.com'

# Gmail App Password
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Debug
EMAIL_TIMEOUT = 30

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Meta WhatsApp Cloud API
META_WHATSAPP_TOKEN = os.getenv('META_WHATSAPP_TOKEN', '')
META_PHONE_NUMBER_ID = os.getenv('META_PHONE_NUMBER_ID', '')
META_VERIFY_TOKEN = os.getenv('META_VERIFY_TOKEN', 'leadcrm123')


TWILIO_ACCOUNT_SID = 'your_sid'
TWILIO_AUTH_TOKEN = 'your_auth_token'
TWILIO_PHONE_NUMBER = '+1XXXXXXXXXX'          # normal calling number
TWILIO_WHATSAPP_NUMBER = 'whatsapp:+1XXXXXXXXXX'  
GOOGLE_CLIENT_ID = 'your_client_id'
GOOGLE_CLIENT_SECRET = 'your_client_secret'
GOOGLE_REDIRECT_URI = 'http://127.0.0.1:8000/google/callback/'

SITE_BASE_URL = 'http://127.0.0.1:8000'  # Twilio ko recording callback ke liye chahiye — public URL hona zaroori hai


# Add these to your existing settings.py (do NOT overwrite the whole file)


# ---------- Base URL ----------
# Must be a publicly reachable HTTPS URL (Twilio & Meta both need to hit your webhooks).
# Use ngrok while testing locally, e.g. https://xxxx.ngrok-free.app
# SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'https://yourdomain.com')

# ---------- Twilio (phone calling) ----------
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')  # e.g. +1XXXXXXXXXX
AGENT_FALLBACK_NUMBER = os.environ.get('AGENT_FALLBACK_NUMBER', '')  # default agent number if none passed

# ---------- Meta WhatsApp Calling API ----------
# Requires: WhatsApp Business Account, Cloud API access, phone number registered
# for calling in Meta Business Manager (Settings > WhatsApp Accounts > Phone numbers > Calling).
META_WA_PHONE_NUMBER_ID = os.environ.get('META_WA_PHONE_NUMBER_ID', '')
META_WA_ACCESS_TOKEN = os.environ.get('META_WA_ACCESS_TOKEN', '')  # system user permanent token
META_WA_API_VERSION = 'v20.0'  # bump as Meta releases newer versions
META_WA_VERIFY_TOKEN = os.environ.get('META_WA_VERIFY_TOKEN', 'change-this-verify-token')  # for webhook verification

# ---------- Google Calendar ----------
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GOOGLE_REDIRECT_URI = SITE_BASE_URL + 'http://127.0.0.1:8000/google/callback/'
GOOGLE_SCOPES = ['https://www.googleapis.com/auth/calendar']

# Never hardcode real secrets in settings.py — load them from environment
# variables or a .env file (python-decouple / django-environ) instead.


# Groq AI

GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')

# ---------- Twilio (phone calling) ----------
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')
AGENT_FALLBACK_NUMBER = os.getenv('AGENT_FALLBACK_NUMBER', '')

# ---------- Site base URL (used for Twilio/Meta webhooks + Google redirect) ----------
SITE_BASE_URL = os.getenv('SITE_BASE_URL', 'http://127.0.0.1:8000')

# ---------- Meta WhatsApp Calling API ----------
META_WA_PHONE_NUMBER_ID = os.getenv('META_WA_PHONE_NUMBER_ID', META_PHONE_NUMBER_ID)
META_WA_ACCESS_TOKEN = os.getenv('META_WA_ACCESS_TOKEN', META_WHATSAPP_TOKEN)
META_WA_API_VERSION = 'v20.0'
META_WA_VERIFY_TOKEN = os.getenv('META_WA_VERIFY_TOKEN', META_VERIFY_TOKEN)

# ---------- Google Calendar ----------
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
GOOGLE_REDIRECT_URI = SITE_BASE_URL + '/google/callback/'
GOOGLE_SCOPES = ['https://www.googleapis.com/auth/calendar']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')

